### ISSUE TITLE
Mobile Meta Tag

### ISSUE THREAD

**Issue by bhk1019** [pawptart/splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

https://github.com/pawptart/splurty/blob/be2d8f73737dad3d87a864a367481719ad0a28c9/app/views/layouts/application.html.erb#L7

**Comment by ty-porter** [comment]
I added the responsive meta tag per the Bootstrap documentation and tested on mobile. It should look better now.
